[pytest]
testpaths = tests

addopts = -ra
asyncio_mode = auto

markers =
    astral: tests for astral_vika SDK
    mcp: tests for vika_mcp tools

log_cli = true
log_cli_level = INFO

filterwarnings =
    ignore::DeprecationWarning